// src/components/ListGroup.tsx
import { useState } from "react";

interface Props {
    items: string[];
    heading: string;
}

function ListGroup({items, heading}: Props) {
    // Hook
    const [selectedIndex, setSelectedIndex] = useState(-1);

    return (
        <>
            <h1>{heading}</h1>
            { items.length === 0 && <p>No Item Found</p>}
            <ul className="list-group">
                {items.map((item, index) => (
                    <li
                        className={ selectedIndex === index ? 'list-group-item active' : 'list-group-item' }
                        key={item}
                        onClick={() => { setSelectedIndex(index);}}
                    >
                        {item}
                    </li>
                ))}
            </ul>
        </>
    );
}

export default ListGroup;

// src/components/ListGroup.vue
<script setup lang="ts">
import { ref } from 'vue';

defineProps<{
  items: string[];
  heading: string;
}>();

const emit = defineEmits<{ selectItem: [item: string] }>();

const selectedIndex = ref(-1);

function select(item: string, index: number) {
  selectedIndex.value = index;
  emit('selectItem', item);
}
</script>

<template>
  <h1>{{ heading }}</h1>
  <p v-if="items.length === 0">No Item Found</p>
  <ul class="list-group">
    <li
      v-for="(item, index) in items"
      :key="item"
      :class="['list-group-item', { active: selectedIndex === index }]"
      @click="select(item, index)"
    >
      {{ item }}
    </li>
  </ul>
</template>
