// src/components/Nav.vue
<script setup lang="ts">
const props = defineProps<{
  base: string;
  path: string;
}>();

const links = [
  { to: '/projects', label: 'Projects' },
  { to: '/contact', label: 'Contact' },
];

const isHome = props.path === '/';
</script>

<template>
  <nav class="nav">
    <ul>
      <li>
        <a :href="`${base}/`" :class="['p-0', { active: isHome }]">
          <img
            class="site-logo"
            :src="`${base}/assets/high-${isHome ? 'black' : 'white'}-trans-logo.png`"
            alt="JonKappa"
            height="64"
            width="100"
          />
        </a>
      </li>
      <li v-for="link in links" :key="link.to" :class="{ active: path === link.to }">
        <a :href="`${base}${link.to}/`">{{ link.label }}</a>
      </li>
    </ul>
  </nav>
</template>

// src/components/Nav.tsx
import { Link, NavLink, useLocation } from 'react-router-dom'

interface Props {
    to: string;
    children: string;
}

function Nav()
{
    return (
        <nav className="nav">

            <ul>
                <li>
                    <NavLink to="/" className="p-0">
                        {({ isActive }) => (
                            <img className="site-logo" src={isActive ? "./assets/high-black-trans-logo.png" : "./assets/high-white-trans-logo.png"} height="64px" width="100px" />
                        )}
                    </NavLink>
                </li>
                <CustomLink to="/projects">Projects</CustomLink>
                <CustomLink to="/contact">Contact</CustomLink>
            </ul>
        </nav>
    )
}

function CustomLink({ to, children, ...props }: Props)
{
    const path = useLocation().pathname;

    const isActive = path === to;

    return (
        <li className={isActive ? "active" : ""}>
            <Link to={to} {...props}>
                {children}
            </Link>
        </li>
    );
}

export default Nav;
